run:
  modules-download-mode: readonly
  tests: true
  allow-parallel-runners: true
output:
  format: colored-line-number
  print-linter-name: true
  print-issued-lines: true
linters:
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - intrange
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - perfsprint
    - predeclared
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - usestdlibvars
    - whitespace
  disable:
    - contextcheck
    - cyclop
    - dupl
    - exhaustruct
    - funlen
    - lll
    - nilnil
    - nlreturn
    - paralleltest
    - prealloc
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (*github.com/simonhull/audiometa.AudioFile).Close
        - (net/http.ResponseWriter).Write
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - diagnostic
        - performance
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104
        - G307
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 5
    revive:
      enable-all-rules: false
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: indent-error-flow
        - name: superfluous-else
        - name: unreachable-code
        - name: unused-parameter
        - name: confusing-naming
    staticcheck:
      checks:
        - all
        - -ST1003
  exclusions:
    generated: lax
    rules:
      - linters:
          - contextcheck
          - errcheck
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - govet
          - nestif
          - nilnil
          - nolintlint
          - revive
          - testifylint
          - thelper
          - unparam
        path: _test\.go
      # Exclude staticcheck QF (quickfix suggestions) from tests
      - linters:
          - staticcheck
        path: _test\.go
        text: "QF"
      - path: _test\.go
        text: 'shadow: declaration of "err"'
      - linters:
          - errcheck
          - gocritic
          - gocyclo
          - gosec
          - nestif
          - revive
        path: cmd/(chaptest|dbinspect|seed)/
      # Exclude internal/errors package naming - it's intentionally named that way
      - linters:
          - revive
        path: internal/errors/
        text: "var-naming"
      # Exclude SSE events comment style - they use grouped comments which is clearer
      - linters:
          - revive
        path: internal/sse/events\.go
        text: "exported"
      # Exclude SSE registration comment style
      - linters:
          - revive
        path: internal/sse/registration\.go
        text: "exported"
      # Exclude "api" package name warning - it's intentional
      - linters:
          - revive
        path: internal/api/
        text: "var-naming.*meaningless package"
      # Exclude recvcheck for time_types - mixed receivers are intentional for json marshal/unmarshal
      - linters:
          - recvcheck
        path: internal/api/time_types\.go
      # Exclude nilerr for store iterators - nil return with error is intentional skip behavior
      - linters:
          - nilerr
        path: internal/store/(contributors|series)\.go
      - linters:
          - gocyclo
          - nestif
        path: internal/api/.*_handlers\.go
      - linters:
          - contextcheck
          - gocritic
          - gocyclo
          - nestif
        path: internal/store/
      - linters:
          - gocritic
          - gocyclo
          - nestif
        path: internal/(dto|media|processor|scanner|search|service)/
      - linters:
          - gosec
        text: G101
      - linters:
          - gosec
        text: G304
      - linters:
          - gosec
        text: G301|G306
      - linters:
          - revive
        path: internal/store/
        text: unused-parameter.*ctx
      - linters:
          - revive
        path: internal/search/
        text: stutters
      - linters:
          - revive
        path: internal/service/
        text: unused-parameter.*ctx
      - linters:
          - staticcheck
        text: SA9003
      - linters:
          - staticcheck
        text: SA6002
      - linters:
          - revive
        path: internal/genre/
        text: stutters
      - linters:
          - goconst
        path: internal/store/
      - linters:
          - nestif
        path: cmd/api/main.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
